language: python
python:
  - "3.7"

install:
  - pip install -r requirements.txt
  - pip install nose mypy flake8 coveralls jingtrang
# JingTrang is installed to check that the configs which are used are valid

# command to run tests
script:
  - nosetests ./tests --with-coverage --cover-package=protogeneia --cover-xml --verbose --nologcapture
  - pyjing protogeneia/schema.rng tests/test_config/*.xml